# Generated by Django 2.1.2 on 2018-12-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propose_join', '0003_auto_20181121_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_event', models.TextField()),
                ('date_of_event_from', models.DateTimeField()),
                ('date_of_event_to', models.DateTimeField()),
                ('time_of_event_from', models.DateTimeField()),
                ('time_of_event_to', models.DateTimeField()),
                ('venue', models.TextField()),
                ('in_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose_join.ExistingClub')),
            ],
        ),
    ]
