# Generated by Django 2.1.2 on 2018-12-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181208_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='datetime_of_event_from',
            new_name='event_from',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='datetime_of_event_to',
            new_name='event_to',
        ),
    ]
