# Generated by Django 2.1.2 on 2018-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181209_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_to',
            field=models.DateTimeField(),
        ),
    ]
