# Generated by Django 2.1.2 on 2018-11-21 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20181118_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onpollclub',
            name='release_date',
            field=models.TimeField(default=datetime.datetime(2018, 11, 21, 8, 54, 21, 685316)),
        ),
    ]
