# Generated by Django 2.1.2 on 2018-11-21 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20181121_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onpollclub',
            name='release_date',
            field=models.TimeField(default=datetime.datetime(2018, 11, 21, 9, 14, 6, 313459)),
        ),
    ]
