# Generated by Django 2.1.2 on 2018-12-11 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20181209_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onpollclub',
            name='release_date',
            field=models.TimeField(default=datetime.datetime(2018, 12, 11, 20, 17, 53, 913761)),
        ),
    ]
