# Generated by Django 2.1.2 on 2018-12-11 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20181211_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onpollclub',
            name='release_date',
            field=models.TimeField(default=datetime.datetime(2018, 12, 11, 22, 11, 51, 850750)),
        ),
    ]
