# Generated by Django 2.1.2 on 2018-12-12 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0017_auto_20181212_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onpollclub',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='onpollclub',
            name='release_date',
        ),
        migrations.AddField(
            model_name='onpollclub',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onpollclub',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onpollclub',
            name='pollend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onpollclub',
            name='club_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
