# Generated by Django 2.1.2 on 2018-11-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('Profession', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'professor'), (3, 'administration')])),
                ('Batch', models.CharField(choices=[('UG1', 'UNDER GRADUATE 1'), ('UG2', 'UNDER GRADUATE 2'), ('UG3', 'UNDER GRADUATE 3'), ('UG4', 'UNDER GRADUATE 4'), ('PG', 'POST GRADUATE ')], max_length=20)),
                ('Dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, unique=True)),
                ('club_info', models.TextField(max_length=20000)),
                ('club_logo', models.ImageField(blank=True, upload_to='media_/club_logo')),
                ('admin', models.ManyToManyField(to='propose_join.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, unique=True)),
                ('club_info', models.TextField(max_length=20000)),
                ('club_logo', models.ImageField(upload_to='media_/club_logo')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propose_join.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='clubmember',
            name='clubs_joined',
            field=models.ManyToManyField(to='propose_join.ExistingClub'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='propose_join.CustomUser'),
        ),
    ]
