# Generated by Django 2.1.2 on 2018-11-21 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propose_join', '0002_auto_20181118_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='clubs_joined',
        ),
        migrations.RemoveField(
            model_name='clubmember',
            name='user_name',
        ),
        migrations.AddField(
            model_name='existingclub',
            name='club_members',
            field=models.ManyToManyField(related_name='club_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='existingclub',
            name='admin',
            field=models.ManyToManyField(related_name='club_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClubMember',
        ),
    ]
