# Generated by Django 2.1.2 on 2018-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='conf_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.CharField(default='', max_length=50),
        ),
    ]
