# Generated by Django 2.1.2 on 2018-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ug',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], default='UG1', max_length=3),
        ),
    ]
