# Generated by Django 2.1.2 on 2018-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_profile_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('N', 'Neutral')], default='N', max_length=1),
        ),
    ]
