# Generated by Django 2.1.2 on 2018-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neutral', 'Neutral')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ug',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4')], default='UG1', max_length=10),
        ),
    ]
