# Generated by Django 2.1.2 on 2018-12-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20181118_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ug',
            field=models.CharField(choices=[('UG1', 'UG1'), ('UG2', 'UG2'), ('UG3', 'UG3'), ('UG4', 'UG4'), ('Phd', 'Phd'), ('PG', 'PG')], default='UG1', max_length=10),
        ),
    ]
